import {createContext, useState, useContext } from 'react'
export const ProductosContext = createContext()

export const productos = [
  {
    id: 1,
    nombre: 'Elden Ring',
    categoria: 'RPG',
    precio: 14999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1245620/header.jpg',
    descripcion: 'Un RPG de acción épico desarrollado por FromSoftware y George R.R. Martin. Explorá el vasto mundo abierto de las Tierras Intermedias y vencé a los semidioses para restaurar el Anillo Ancestral.',
    descripcion_breve: 'RPG de acción en mundo abierto',
    caracteristicas: ['Mundo abierto', 'Multijugador online', 'Más de 100 horas de contenido', 'DLC incluido'],
    stock: 8,
  },
  {
    id: 2,
    nombre: 'Cyberpunk 2077',
    categoria: 'RPG',
    precio: 9999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1091500/header.jpg',
    descripcion: 'Sumergite en Night City, una megalópolis obsesionada con el poder y las modificaciones corporales. Un RPG de acción en primera persona con una narrativa profunda.',
    descripcion_breve: 'Aventura futurista',
    caracteristicas: ['Mundo abierto masivo', 'Historia ramificada', 'Expansión Phantom Liberty', 'Ray Tracing'],
    stock: 15,
  },
  {
    id: 3,
    nombre: 'God of War Ragnarök',
    categoria: 'Acción',
    precio: 19999,
    imagen: 'https://image.api.playstation.com/vulcan/ap/rnd/202207/1210/4xJ8XB3bi888QTLZYdl7Oi0s.png',
    descripcion: 'Kratos y Atreus deben viajar a cada uno de los Nueve Reinos para enfrentar el inminente Ragnarök. Una aventura épica que define una generación.',
    descripcion_breve: 'Aventura épica',
    caracteristicas: ['Historia épica', 'Gráficos next-gen', 'Duración 40+ horas', 'Premio GOTY'],
    stock: 5,
  },
  {
    id: 4,
    nombre: 'The Legend of Zelda: Tears of the Kingdom',
    categoria: 'Aventura',
    precio: 17999,
    imagen: 'https://assets.nintendo.com/image/upload/ar_16:9,c_lpad,w_656/b_white/f_auto/q_auto/ncom/software/switch/70010000063714/ec9a748df75cb2f9e4c72c9d4e40b09f4a35b08eb61e8a7f4b12bc8e9f11fb05',
    descripcion: 'Explorá los cielos y las profundidades de Hyrule. Con nuevos poderes y materiales infinitos, construí y creá soluciones únicas para cada desafío.',
    descripcion_breve: 'Aventura en el mundo de Hyrule',
    caracteristicas: ['Construcción sandbox', 'Mundo abierto 3D', 'Más de 60 mazmorras', 'Física avanzada'],
    stock: 3,
  },
  {
    id: 5,
    nombre: 'Counter-Strike 2',
    categoria: 'FPS',
    precio: 0,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/730/header.jpg',
    descripcion: 'El FPS competitivo más popular del mundo, ahora con motor Source 2. Gráficos mejorados, smokes volumétricas y servidores de alta calidad.',
    descripcion_breve: 'FPS competitivo',
    caracteristicas: ['Free to Play', 'Motor Source 2', 'Competitivo 5v5', 'Actualizaciones constantes'],
    stock: 99,
  },
  {
    id: 6,
    nombre: 'Red Dead Redemption 2',
    categoria: 'Aventura',
    precio: 11999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1174180/header.jpg',
    descripcion: 'Una historia épica del corazón de América. Seguí a Arthur Morgan, forajido del Viejo Oeste, en una aventura de traición, supervivencia y redención.',
    descripcion_breve: 'Aventura del Viejo Oeste',
    caracteristicas: ['Mundo vivo y dinámico', 'Historia aclamada', 'Modo online', 'Detalles increíbles'],
    stock: 0,
  },
  {
    id: 7,
    nombre: 'Baldur\'s Gate 3',
    categoria: 'RPG',
    precio: 16999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1086940/header.jpg',
    descripcion: 'El RPG por turnos más galardonado de la historia moderna. Basado en D&D 5e, ofrece libertad total para explorar, combatir y contar tu historia.',
    descripcion_breve: 'RPG por turnos',
    caracteristicas: ['Co-op 4 jugadores', 'Más de 174 horas', 'Múltiples finales', 'GOTY 2023'],
    stock: 12,
  },
  {
    id: 8,
    nombre: 'FIFA 25',
    categoria: 'Deportes',
    precio: 13999,
    imagen: 'https://image.api.playstation.com/vulcan/ap/rnd/202408/2321/9ac0cac4ed7d53e7c1ed52dda7e70c61b19b55ec6b59dc0b.png',
    descripcion: 'La experiencia de fútbol más realista. FC IQ, estilos de juego avanzados y el modo Ultimate Team renovado para la temporada 2025.',
    descripcion_breve: 'Juego de fútbol realista',
    caracteristicas: ['FC IQ', 'Modos online y offline', 'Ligas y selecciones oficiales', 'Cross-play'],
    stock: 20,
  },
  {
    id: 9,
    nombre: 'Hollow Knight',
    categoria: 'Indie',
    precio: 3499,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/367520/header.jpg',
    descripcion: 'Un metroidvania de acción y aventura ambientado en un vasto mundo subterráneo de insectos. Arte hermoso, desafío real y una historia misteriosa.',
    descripcion_breve: 'Metroidvania de acción',
    caracteristicas: ['Más de 40 horas', 'Jefes épicos', 'Arte dibujado a mano', 'DLCs gratuitos'],
    stock: 50,
  },
  {
    id: 10,
    nombre: 'Call of Duty: Black Ops 6',
    categoria: 'FPS',
    precio: 18999,
    imagen: 'https://www.callofduty.com/content/dam/atvi/callofduty/cod-touchui/blog/hero/mw-cod/BO6-Key-Art.jpg',
    descripcion: 'El regreso del modo campaña premium de Call of Duty. Acción omnidireccional, movimiento fluido y un modo Zombies renovado con más mapas que nunca.',
    descripcion_breve: 'FPS con modo campaña',
    caracteristicas: ['Campaña 15+ horas', 'Multiplayer 6v6', 'Zombies', 'Warzone integrado'],
    stock: 7,
  },
  {
    id: 11,
    nombre: 'Stardew Valley',
    categoria: 'Indie',
    precio: 2999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/413150/header.jpg',
    descripcion: 'Construí la granja de tus sueños, exploralas minas, hacete amigo de los vecinos del pueblo y disfrutá de cientos de horas en este RPG de simulación.',
    descripcion_breve: 'RPG de simulación',
    caracteristicas: ['Multijugador hasta 4', 'Actualizaciones gratuitas', 'Cross-save', 'Relajante y profundo'],
    stock: 99,
  },
  {
    id: 12,
    nombre: 'Spider-Man 2',
    categoria: 'Acción',
    precio: 21999,
    imagen: 'https://image.api.playstation.com/vulcan/ap/rnd/202306/1219/1c7b75d8fe814b0f83a5b83f4f28b6dae43e57bcca8e39ac.png',
    descripcion: 'Peter Parker y Miles Morales regresan en una nueva aventura de Spider-Man. Enfrentá a Venom en un Nueva York más grande y detallado que nunca.',
    descripcion_breve: 'Aventura de Spider-Man',
    caracteristicas: ['Exclusivo PS5', 'Mundo abierto NYC', 'Dos protagonistas', 'Ray Tracing 60fps'],
    stock: 0,
  },
  {
    id: 13,
    nombre: 'Minecraft',
    categoria: 'Sandbox',
    precio: 4999,
    imagen: 'https://www.minecraft.net/content/dam/minecraftnet/games/minecraft/key-art/Games_Minecraft_KeyArt_Hero-card_800x450.jpg',
    descripcion: 'El juego más vendido de la historia. Construí, explorá y sobrevivé en un mundo infinito generado por procedimientos. Sin límites para la creatividad.',
    descripcion_breve: 'Juego de construcción',
    caracteristicas: ['Modo creativo y survival', 'Mods ilimitados', 'Multiplayer', 'Actualizaciones gratuitas'],
    stock: 99,
  },
  {
    id: 14,
    nombre: 'Street Fighter 6',
    categoria: 'Peleas',
    precio: 12999,
    imagen: 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1364780/header.jpg',
    descripcion: 'La nueva era del rey de los juegos de pelea. Con el modo World Tour, Battle Hub y un sistema de combate revolucionario con el Drive System.',
    descripcion_breve: 'Juego de pelea',
    caracteristicas: ['18 personajes base', 'Modo historia', 'Cross-play', 'Torneos online'],
    stock: 10,
  },
]

// export const categorias = ['Todas', ...new Set(productos.map(p => p.categoria))]